//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.dataaccess.com/webservicesserver/", ConfigurationName="NumberConversionSoapType")]
public interface NumberConversionSoapType {
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="")]
    string NumberToWords(ulong ubiNum);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="")]
    string NumberToDollars(decimal dNum);
}

public interface NumberConversionSoapTypeChannel : NumberConversionSoapType, System.ServiceModel.IClientChannel {
}

public class NumberConversionSoapTypeClient : System.ServiceModel.ClientBase<NumberConversionSoapType>, NumberConversionSoapType {
    
    public NumberConversionSoapTypeClient() {
    }
    
    public NumberConversionSoapTypeClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public NumberConversionSoapTypeClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public NumberConversionSoapTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public NumberConversionSoapTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public string NumberToWords(ulong ubiNum) {
        return base.Channel.NumberToWords(ubiNum);
    }
    
    public string NumberToDollars(decimal dNum) {
        return base.Channel.NumberToDollars(dNum);
    }
}
namespace www.dataaccess.com.webservicesserver {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NumberToWords", Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToWords : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ulong ubiNumField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ulong ubiNum {
            get {
                return this.ubiNumField;
            }
            set {
                this.ubiNumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NumberToWordsResponse", Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToWordsResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NumberToWordsResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string NumberToWordsResult {
            get {
                return this.NumberToWordsResultField;
            }
            set {
                this.NumberToWordsResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NumberToDollars", Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToDollars : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal dNumField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal dNum {
            get {
                return this.dNumField;
            }
            set {
                this.dNumField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NumberToDollarsResponse", Namespace="http://www.dataaccess.com/webservicesserver/")]
    public partial class NumberToDollarsResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NumberToDollarsResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string NumberToDollarsResult {
            get {
                return this.NumberToDollarsResultField;
            }
            set {
                this.NumberToDollarsResultField = value;
            }
        }
    }
}
